### ISSUE TITLE
memoryerror: std::bad_alloc

### ISSUE THREAD

**Issue by xijiz** [nlpaueb/deep-relevance-ranking#2]
When I train the dataset "robust04_data" and it goes to "Making Dev preds", it throws  an error: "MemoryError: std::bad_alloc". More detailed information follows:
Traceback (most recent call last):
  File "drmm_main.py", line 137, in <module>
    rel_scores[j] = score.value()
  File "_dynet.pyx", line 1817, in _dynet.Expression.value
  File "_dynet.pyx", line 1831, in _dynet.Expression.value
MemoryError: std::bad_alloc
And I don't know how to solve it.

**Comment by fj-morales** [comment]
Hi there, 

I am facing the same problem. Is there any fix? Could you please provide the code?

Thanks in advance!
